/-
Copyright (c) 2026 IUT Lean formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: IUT Lean formalization contributors
-/
import Iut.Foundations.SourceHodgeArakelovEvaluation
import Iut.Foundations.SourceSplitKummerFrobenioid
import Iut.Foundations.SourceArchimedeanKummerSystem
import Iut.Foundations.SourceModelFrobenioidPreStepFactorization
import Iut.Foundations.SourceTheorem311

open Iut

/-!
# M1-M3 source endpoint axiom audit

This audit keeps the source-faithful Kummer and pointed-restriction endpoints
visible to Lean's axiom reporter.
-/

#print axioms Iut.SourceMLFIntegralMonoid.galoisAction
#print axioms Iut.SourceKummerFaithfulness.eq_one_of_roots_in_profinite
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnity_finite
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rationalCircle_torsion_natCard
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnityEquiv
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnity_natCard
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnityGroup_natCard
#print axioms Iut.SourceMonoidCyclotome.boundedCoe_isClosedEmbedding
#print axioms Iut.SourceMonoidCyclotome.asProfinite
#print axioms Iut.SourceMonoidCyclotome.eq_one_of_roots
#print axioms Iut.SourceMLFIntegralMonoid.groupificationToAlgebraicClosureUnits_surjective
#print axioms Iut.SourceMLFIntegralMonoid.groupificationEquivAlgebraicClosureUnits
#print axioms Iut.SourceMLFIntegralMonoid.torsionUnit_image
#print axioms Iut.SourceMLFGaloisTMPair.augmentation_surjective
#print axioms Iut.SourceMLFGaloisTMPair.openStabilizer_fixed
#print axioms Iut.SourceMLFGaloisTMPair.continuousCyclotomeAction
#print axioms Iut.SourceMLFGaloisTMPair.unitModuloTorsion_eq_one_iff
#print axioms Iut.SourceMLFGaloisTMPair.unitAction_mem_torsion_iff
#print axioms Iut.SourceMLFGaloisTMPair.unitModuloTorsionActionHom_mk
#print axioms Iut.SourceMLFGaloisTMPair.unitModuloTorsionActionMulAut_mk
#print axioms Iut.SourceMLFGaloisTMPair.TimesMuKummerIsomorphism.sourceDifference_smul_first
#print axioms Iut.SourceMLFGaloisTMPair.TimesMuKummerIsomorphism.orbitOf_eq
#print axioms Iut.SourceSplitKummerMonoid.unitQuotient_isUnit_eq_one
#print axioms Iut.SourceMLFGaloisTMPair.badTimesMuUnitsEquiv
#print axioms Iut.SourceMLFGaloisTMPair.goodTimesMuUnitsEquiv
#print axioms Iut.SourceMLFGaloisTMPair.unitAction_mem_rootsOfUnity_iff
#print axioms Iut.SourceMLFGaloisTMPair.badPerpMonoid_stable
#print axioms Iut.SourceMLFGaloisTMPair.badCharacteristicAction_mk
#print axioms Iut.SourceMLFGaloisTMPair.badTimesMuUnitsEquiv_equivariant
#print axioms Iut.SourceMLFGaloisTMPair.goodTimesMuUnitsEquiv_equivariant
#print axioms Iut.SourceArchimedeanKummerSystem.rootsOfUnity_isClosed
#print axioms Iut.SourceArchimedeanKummerSystem.continuousQuotientMap_isOpenQuotientMap
#print axioms Iut.SourceArchimedeanKummerSystem.rootsOfUnity_le_of_dvd
#print axioms Iut.SourceArchimedeanKummerSystem.transition_ker
#print axioms Iut.SourceArchimedeanKummerSystem.continuousTransition_comp
#print axioms Iut.SourceArchimedeanKummerSystem.orientedQuotientMap_ker
#print axioms Iut.SourceArchimedeanKummerSystem.continuousOrientedQuotientMap_isOpenQuotientMap
#print axioms Iut.SourceArchimedeanKummerSystem.orientationAutomorphism_ne
#print axioms Iut.SourceArchimedeanKummerSystem.unitQuotientDiagram
#print axioms Iut.SourceArchimedeanKummerSystem.restrictedOrientedQuotientNaturalTransformation
#print axioms Iut.SourceModelFrobenioid.gpPullback_id
#print axioms Iut.SourceModelFrobenioid.gpPullback_comp
#print axioms Iut.SourceModelFrobenioid.Input.gpPullback_mem_birationalDivisors
#print axioms Iut.SourceModelFrobenioid.Hom.comp
#print axioms Iut.SourceModelFrobenioid.Carrier.comp_rationalFunction
#print axioms Iut.SourceModelFrobenioid.Carrier.structureFunctor
#print axioms Iut.SourceModelFrobenioid.Carrier.grothendieck_add_denominator
#print axioms Iut.SourceModelFrobenioid.Carrier.commonLower_add_left
#print axioms Iut.SourceModelFrobenioid.Carrier.commonLower_add_right
#print axioms Iut.SourceModelFrobenioid.Carrier.localizationRepresentative
#print axioms Iut.SourceModelFrobenioid.Carrier.commonPreSteps
#print axioms Iut.SourceModelFrobenioid.Carrier.pullbackArrow_isPullback
#print axioms Iut.SourceModelFrobenioid.Carrier.pullbackSliceProjection_bijective
#print axioms Iut.SourceModelFrobenioid.Carrier.pullbackBaseSlices
#print axioms Iut.SourceModelFrobenioid.Carrier.value_eq_zeroObject
#print axioms Iut.SourceModelFrobenioid.Carrier.isConnected
#print axioms Iut.SourceModelFrobenioid.Carrier.epi
#print axioms Iut.SourceModelFrobenioid.Carrier.preFrobenioidPresentation
#print axioms Iut.SourceModelFrobenioid.Carrier.inverseOfPreStepIsometric
#print axioms Iut.SourceModelFrobenioid.Carrier.isIso_of_preStep_isometric
#print axioms Iut.SourceModelFrobenioid.Carrier.isIsotropic
#print axioms Iut.SourceModelFrobenioid.Carrier.isCoAngular
#print axioms Iut.SourceModelFrobenioid.Carrier.isOfFrobeniusType_iff
#print axioms Iut.SourceModelFrobenioid.Carrier.zeroFrobeniusTrivialization
#print axioms Iut.SourceModelFrobenioid.Carrier.baseRepresented
#print axioms Iut.SourceModelFrobenioid.Carrier.frobeniusDegreeWitness
#print axioms Iut.SourceModelFrobenioid.Carrier.isotropicHull
#print axioms Iut.SourceModelFrobenioid.Carrier.coAngular_comp
#print axioms Iut.SourceModelFrobenioid.Carrier.baseIsoTransportEquiv
#print axioms Iut.SourceModelFrobenioid.Carrier.baseIsoTransport_conjugates
#print axioms Iut.SourceModelFrobenioid.Carrier.unitTransport
#print axioms Iut.SourceModelFrobenioid.Carrier.unitTransport_unique
#print axioms Iut.SourceModelFrobenioid.Carrier.unitTransport_dependsOnlyOnBase
#print axioms Iut.SourceModelFrobenioid.Carrier.outgoingDivisorRepresentative
#print axioms Iut.SourceModelFrobenioid.Carrier.outgoingDivisorOrderFullyFaithful
#print axioms Iut.SourceModelFrobenioid.Carrier.outgoingDivisorRepresentative_unique
#print axioms Iut.SourceModelFrobenioid.Carrier.incomingDivisor
#print axioms Iut.SourceModelFrobenioid.Carrier.incomingDivisorRepresentative
#print axioms Iut.SourceModelFrobenioid.Carrier.incomingDivisorOrderFullyFaithful
#print axioms Iut.SourceModelFrobenioid.Carrier.incomingDivisorRepresentative_unique
#print axioms Iut.SourceModelFrobenioid.Carrier.factorization
#print axioms Iut.SourceModelFrobenioid.Carrier.isIso_linear_isometric
#print axioms Iut.SourceModelFrobenioid.Carrier.pullback_linear_lbInvertible
#print axioms Iut.SourceModelFrobenioid.Carrier.factorizationPullbackComparison
#print axioms Iut.SourceModelFrobenioid.Carrier.factorizationFrobeniusComparison
#print axioms Iut.SourceModelFrobenioid.Carrier.factorizationIso
#print axioms Iut.SourceModelFrobenioid.Carrier.factorizationIso_unique
#print axioms Iut.SourceModelFrobenioid.Carrier.preStep_mono
#print axioms Iut.SourceModelFrobenioid.Carrier.preStep_coAngularThenIsometric
#print axioms Iut.SourceModelFrobenioid.Carrier.preStep_isometricThenCoAngular
#print axioms Iut.SourceModelFrobenioid.Carrier.preStepFactorizationIso
#print axioms Iut.SourceModelFrobenioid.Carrier.preStepFactorizationIso_unique
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootSystem.ofModel
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootSystem.quotientUnit_exists
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootRealization.ofRootSystem
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootComparison.ofModel
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootTheory.chosen_rootSystem
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootRealization.ratioCyclotome_mul_group
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootRealization.ratioCyclotome_continuous
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootComparison.germ_eq
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootTheory.kummerValue_mul
#print axioms Iut.SourceMLFGaloisTMPair.LocalKummerRootTheory.local_toGerm_eq_global
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootTheory.canonicalKummerMap
#print axioms Iut.SourceMLFGaloisTMPair.LocalKummerRootTheory.canonicalKummerMap
#print axioms Iut.SourceMLFGaloisTMPair.LocalKummerRootTheory.canonicalKummerMap_toGerm
#print axioms Iut.SourceIUTIIUnitKummerEmbedding.unitKummer_injective
#print axioms Iut.SourceIUTIIUnitKummerEmbedding.torsionUnitImage_eq_constant_torsion
#print axioms Iut.sourceConstantTorsion_unitKummer
#print axioms Iut.SourceIUTIICorollary112PointedRestriction.detects_constant_torsion
#print axioms Iut.SourceIUTIICorollary112PointedRestriction.splittingUpToTorsion
#print axioms Iut.SourceIUTIIValueProfile.natCard_eq_twoEll_pow_lStar
#print axioms Iut.SourceIUTIIMultiplicativeTorsionAction.actionMap_injective
#print axioms Iut.SourceIUTIIHodgeArakelovThetaPilot.valueProfiles_natCard
#print axioms Iut.SourceIUTIIHodgeArakelovThetaPilot.zeroTheta_carrier_subset_torsion
#print axioms Iut.IUTIIAbsoluteThetaLabel.card_eq_lPlusMinus
#print axioms Iut.SourceIndTopologicalLocalFieldPresentation.transition_id
#print axioms Iut.SourceIndTopologicalLocalFieldPresentation.transition_comp
#print axioms Iut.SourceSelectedFinitePlace.toSelected
#print axioms Iut.SourceSelectedInfinitePlace.toSelected
#print axioms Iut.SourceSelectedPlace.LogFieldCarrier

namespace Iut.SourceFiniteLocalFieldStages

#print axioms transitionLinearMap
#print axioms transitionContinuousLinearMap
#print axioms stageDiagram
#print axioms moduleCocone
#print axioms moduleIsColimit
#print axioms stageField
#print axioms module
#print axioms fieldPresentation
#print axioms toAlgebraicClosureLinearMap
#print axioms toAlgebraicClosureLinearMap_injective
#print axioms toAlgebraicClosureLinearMap_surjective
#print axioms carrierEquivAlgebraicClosure
#print axioms selectedCompletionEmbedding
#print axioms continuous_selectedCompletionEmbedding
#print axioms stage_fixingSubgroup_isOpen
#print axioms stage_fixedField_fixingSubgroup
#print axioms selectedCompletionBasis
#print axioms selectedStageGenerators
#print axioms selectedStage
#print axioms selectedCompletionEmbedding_mem_selectedStage
#print axioms stageEmbeddingUlift
#print axioms carrierEquivLogFieldCarrier
#print axioms localFieldRealization

end Iut.SourceFiniteLocalFieldStages

namespace Iut.SourceInfiniteLocalFieldStages

#print axioms rationalPlace_isReal
#print axioms rationalCompletionEquivReal
#print axioms rationalCompletionEmbedding
#print axioms continuous_rationalCompletionEmbedding
#print axioms complexScalarTower
#print axioms complexFiniteDimensional
#print axioms stageField
#print axioms stageDiagram
#print axioms module
#print axioms fieldPresentation
#print axioms selectedCompletionEmbedding
#print axioms continuous_selectedCompletionEmbedding
#print axioms selectedCompletionEmbedding_injective
#print axioms selectedBaseCompletionRingHom
#print axioms continuous_selectedBaseCompletionRingHom
#print axioms selectedCompletionEmbedding_algebraMap
#print axioms selectedCompletion_finiteDimensional
#print axioms selectedCompletion_isAlgebraicClosure
#print axioms stageEmbeddingUlift
#print axioms carrierEquivLogFieldCarrier
#print axioms localFieldRealization

end Iut.SourceInfiniteLocalFieldStages

#print axioms Iut.SourceMonoAnalyticLogShell.fieldPresentation
#print axioms Iut.SourceMonoAnalyticIntegralStructure.isClosed_logShellCarrier
#print axioms Iut.SourceMonoAnalyticIntegralStructure.logShellCarrier_eq_lattice
#print axioms Iut.SourceMonoAnalyticIntegralStructure.logShellCarrier_eq_piBall
#print axioms Iut.sourcePStar_pos
#print axioms Iut.sourcePStar_ne_zero
#print axioms Iut.SourceRationalPlace.residuePrime_prime
#print axioms Iut.SourceNonarchimedeanLogShellDefinition.preLogShell_isCompact
#print axioms Iut.SourceNonarchimedeanLogShellDefinition.Transport.preLogShell_image
#print axioms Iut.SourceArchimedeanLogShellDefinition.lowerEndpoint_mem
#print axioms Iut.SourceArchimedeanLogShellDefinition.upperEndpoint_mem
#print axioms Iut.SourceArchimedeanLogShellDefinition.upperEndpoint_sub_lowerEndpoint
#print axioms Iut.SourceArchimedeanLogShellDefinition.neg_mem_iff
#print axioms Iut.SourceArchimedeanLogShellDefinition.rotationOrbit_eq_closedBall
#print axioms Iut.SourceArchimedeanLogShellDefinition.complexExponential_isCoveringMap
#print axioms Iut.SourceArchimedeanLogShellDefinition.complexExponential_eq_one_iff
#print axioms Iut.SourceArchimedeanLogShellDefinition.rootQuotient_deckGroup_eq_rootsOfUnity
#print axioms Iut.SourceArchimedeanLogShellDefinition.rootQuotientPowerLift_isQuotientMap
#print axioms Iut.SourceArchimedeanLogShellDefinition.rootQuotientExponential_zero
#print axioms Iut.SourceArchimedeanLogShellDefinition.rootQuotientHomeomorphUnits_exponential
#print axioms Iut.SourceArchimedeanLogShellDefinition.rootQuotientExponential_isCoveringMap
#print axioms Iut.SourceArchimedeanLogShellDefinition.rootQuotientExponential_eq_one_iff
#print axioms Iut.SourceArchimedeanLogShellDefinition.rootQuotientExponential_eq_one_iff_mem_periodLattice
#print axioms Iut.SourceArchimedeanLogShellDefinition.quotientLowerEndpoint_mem
#print axioms Iut.SourceArchimedeanLogShellDefinition.quotientUpperEndpoint_mem
#print axioms Iut.SourceArchimedeanLogShellDefinition.quotientUpperEndpoint_sub_lowerEndpoint
#print axioms Iut.SourceArchimedeanLogShellDefinition.image_quotientFundamentalSegment
#print axioms Iut.SourceArchimedeanLogShellDefinition.exponential_isCoveringMap
#print axioms Iut.SourceArchimedeanLogShellDefinition.exponential_eq_one_iff
#print axioms Iut.SourceArchimedeanLogShellDefinition.image_piBall_eq_rotationOrbit
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.sourceDefinition_residuePrime
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transport_preLogShell
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.sourceLocalUnitsEquiv_id
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.sourceLocalUnitsEquiv_comp
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transport_logShell
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transport_measuredRegion
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transport_logVolume

#print axioms Iut.SourceMonoAnalyticTensorPacket.ind2CoordinateIndex_card
#print axioms Iut.SourceMonoAnalyticTensorPacket.placeTupleIndex_card
#print axioms Iut.SourcePacketFiniteFieldDecomposition.fieldSummandIndex_card
#print axioms Iut.SourceMonoAnalyticTensorPacket.inverse_tprod_mem_distinguishedSubmodule
#print axioms Iut.SourceTheorem311Ind1Action.ofProcessionFunctor_act_apply
#print axioms Iut.CategoryProcession.MemberHom.componentSelf_comp
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.factorTransport_comp
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.TensorTopology.reindexLinearEquiv_trans
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.packetMemberTransport_id
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.packetMemberTransport_comp
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.packetInd1Action
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.localInd1PacketAction
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.LocalConstruction.toLocalInd1Action
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.PresentationConstruction.toInd1Action
#print axioms Iut.SourceDThetaBridgeCore.IsomorphismMember.processionObjectIso
#print axioms Iut.SourceDThetaBridgeCore.IsomorphismMember.monoAnalyticProcessionMemberObjectIso
#print axioms Iut.SourceLGPGaussianLogThetaLattice.verticalCoricityToCommon
#print axioms Iut.SourceTheorem311Ind2SummandAction.factorAction_on_summand
#print axioms Iut.SourceTheorem311Ind2SummandAction.packetAction_mul
#print axioms Iut.SourceTheorem311LocalInd2Action.action_apply
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.ind2ActionAbove_mul
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.localInd2Action
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.LocalConstruction.toLocalInd2Action
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.factorTransport_on_summand
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.TensorTopology.congr_distinguishedSubmodule
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.tensorPacketKummerIso
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketKummerIso
#print axioms Iut.SourceTheorem311LocalData.processionLogVolume
#print axioms Iut.SourceNormalizedLogVolume.PacketNormalization.valueOn_dilateRegion
#print axioms Iut.SourceSelectedPlace.moduliLocalDegree
#print axioms Iut.SourceSelectedPlace.moduliRationalLocalDegree
#print axioms Iut.ThetaFinitePlace.completionNontriviallyNormedField
#print axioms Iut.ThetaFinitePlace.completionSecondCountableTopology
#print axioms Iut.ThetaFinitePlace.rationalCompletionLocallyCompactSpace
#print axioms Iut.ThetaFinitePlace.underlyingPrime_comap_asIdeal
#print axioms Iut.ThetaFinitePlace.rationalValuation_isEquiv_restriction
#print axioms Iut.ThetaFinitePlace.rationalWithValMap_uniformContinuous
#print axioms Iut.ThetaFinitePlace.rationalDenseRingHom
#print axioms Iut.ThetaFinitePlace.continuous_rationalDenseRingHom
#print axioms Iut.ThetaFinitePlace.completionRingHom
#print axioms Iut.ThetaFinitePlace.continuous_completionRingHom
#print axioms Iut.ThetaFinitePlace.completionRingHom_ratCast
#print axioms Iut.ThetaFinitePlace.completionAlgebra
#print axioms Iut.ThetaFinitePlace.completionContinuousSMul
#print axioms Iut.ThetaFinitePlace.completionScalarTower
#print axioms Iut.ThetaFinitePlace.finiteDimensional
#print axioms Iut.ThetaFinitePlace.properSpace
#print axioms Iut.SourceTopologicalLocalField.ofFinitePlace
#print axioms Iut.SourceTopologicalLocalField.finitePlaceIntegerRing_mem_iff_norm_le_one
#print axioms Iut.SourceTopologicalLocalField.finitePlaceIntegerRing_isCompact
#print axioms Iut.SourceTopologicalLocalField.finitePlaceIntegerRing_isOpen
#print axioms Iut.SourceNonarchimedeanLocalFieldIntegers.ofFinitePlace

namespace Iut.SourceTopologicalLocalField.LocalDegreeTower

#print axioms localDegree_eq_relativeDegree_mul_moduliDegree

end Iut.SourceTopologicalLocalField.LocalDegreeTower

namespace Iut.SourcePacketFiniteFieldStage

#print axioms localTensor_finrank
#print axioms field_finrank_sum
#print axioms field_finrank_sum_eq_factor_finrank_product

end Iut.SourcePacketFiniteFieldStage

namespace Iut.SourceNonarchimedeanLocalFieldIntegers

#print axioms normalizedLogVolume_value_eq_zero
#print axioms Iut.ThetaFinitePlace.residueCharacteristic_eq_natGenerator
#print axioms rationalPrime_eq_residueCharacteristic
#print axioms rationalPrime_prime
#print axioms log_rationalPrimeScale
#print axioms localPrimeLogVolumeShift_eq_degree_mul_packetLogVolumeShift
#print axioms rationalPrimeQuotientModule
#print axioms padicScalarFieldMap
#print axioms continuous_padicScalarFieldMap
#print axioms padicScalarFieldMap_mem_integerRing
#print axioms padicScalarMap
#print axioms continuous_padicScalarMap
#print axioms padicFieldRingHom
#print axioms continuous_padicFieldRingHom
#print axioms padicScalarMap_coe_eq_padicFieldRingHom
#print axioms padicIntegerFieldRingHom
#print axioms padicFieldBasis
#print axioms eventually_padicPrime_pow_smul_basis_mem
#print axioms padicIntegralScaleExponent
#print axioms padicIntegralScaleExponent_spec
#print axioms scaledPadicFieldBasis
#print axioms scaledPadicFieldBasis_apply
#print axioms integralBasisVector
#print axioms padicBasisLattice
#print axioms padicBasisLattice_fg
#print axioms padicBasisLattice_isOpen
#print axioms integerAddSubgroupModuleFinite
#print axioms integerSubringModuleFinite
#print axioms isIntegral_iff_mem_integerRing
#print axioms padicIsIntegralClosure
#print axioms padicIntegralBasis
#print axioms PAdicIntegralClosure.padicPrime_smul
#print axioms PAdicIntegralClosure.coefficientReduction_surjective
#print axioms PAdicIntegralClosure.coefficientReduction_ker
#print axioms PAdicIntegralClosure.quotientLinearEquiv
#print axioms PAdicIntegralClosure.quotient_finrank_eq
#print axioms PAdicIntegralClosure.toRationalPrimeResidueModule
#print axioms RationalPrimeResidueModule.quotientFintype
#print axioms RationalPrimeResidueModule.quotient_card_eq
#print axioms ResidueQuotientFormula.residueCosets_cover_integerRing
#print axioms ResidueQuotientFormula.residueCosets_pairwiseDisjoint
#print axioms ResidueQuotientFormula.scaledRing_measure_eq_scale
#print axioms ResidueQuotientFormula.toHaarDegreeFormula
#print axioms normalizedHaarMeasure_rationalPrimeDilation
#print axioms normalizedLogVolume_admissible_rationalPrimeDilation
#print axioms normalizedLogVolume_rawLogVolume_rationalPrimeDilation
#print axioms normalizedLogVolume_valueOn_rationalPrimeDilation

end Iut.SourceNonarchimedeanLocalFieldIntegers

#print axioms Iut.SourcePacketMeasuredField.NonarchimedeanPrimeDilation.ofIntegers

namespace Iut.SourcePacketFiniteMeasuredFieldDecomposition

#print axioms blockFieldDecomposition_image_blockFieldProductRegion
#print axioms blockRadializedRegion_blockFieldProductRegion
#print axioms blockProductMeasure_blockFieldProductRegion
#print axioms blockVolume_valueOn_blockFieldProductAdmissibleRegion

end Iut.SourcePacketFiniteMeasuredFieldDecomposition

namespace Iut.SourcePacketFiniteStageLogVolume.DirectProductPrimeNormalization

#print axioms factor_localDegree
#print axioms block_degree_sum
#print axioms blockDilation_image_blockFieldProductRegion
#print axioms blockVolume_valueOn_dilatedFieldRegions_eq_degreeProduct
#print axioms stageDilation_image_packetAdmissibleRegion
#print axioms valueOn_dilatedPacketAdmissibleRegion

end Iut.SourcePacketFiniteStageLogVolume.DirectProductPrimeNormalization

#print axioms Iut.SourcePacketMeasuredField.ofNonarchimedean
#print axioms Iut.SourceArchimedeanLocalFieldModel.complexNorm_image_integralRegion
#print axioms Iut.SourceArchimedeanLocalFieldModel.radialLengthMeasure_unitRadialInterval
#print axioms Iut.SourceArchimedeanLocalFieldModel.completedRadialLengthMeasure_image_integralRegion
#print axioms Iut.SourceArchimedeanLocalFieldModel.normalizedLogVolume_value_eq_zero
#print axioms Iut.SourceArchimedeanLocalFieldModel.addCircleVolume_image_of_injOn
#print axioms Iut.SourceArchimedeanLocalFieldModel.angularLengthMeasure_univ
#print axioms Iut.SourceArchimedeanLocalFieldModel.angularLengthMeasure_mul_image
#print axioms Iut.SourceArchimedeanLocalFieldModel.continuous_complexAngularProjection

namespace Iut.SourceArchimedeanLocalFieldModel.AngularRegion

#print axioms angularVolume_pos
#print axioms angularVolume_lt_top
#print axioms angularVolume_mulLeft
#print axioms angularLogVolume_mulLeft

end Iut.SourceArchimedeanLocalFieldModel.AngularRegion

namespace Iut.SourceArchimedeanLocalFieldModel.ExponentialRegion

#print axioms angularLengthMeasure_angularImage
#print axioms completedRadialLengthMeasure_fieldCarrier_eq_angular
#print axioms normalizedLogVolume_valueOn_eq_angularLogVolume

end Iut.SourceArchimedeanLocalFieldModel.ExponentialRegion

#print axioms Iut.SourceArchimedeanLocalFieldModel.radialLengthMeasure_packetScale
#print axioms Iut.SourceArchimedeanLocalFieldModel.radialization_image_packetDilation
#print axioms Iut.SourceArchimedeanLocalFieldModel.completedRadialLengthMeasure_packetDilation
#print axioms Iut.SourceArchimedeanLocalFieldModel.packetNormalization
#print axioms Iut.SourcePacketMeasuredField.ofArchimedean
#print axioms Iut.SourcePacketMeasuredField.integral_measure_eq_one
#print axioms Iut.SourcePacketMeasuredField.normalizationOffset_eq_zero
#print axioms SourcePacketFiniteFieldDecomposition.stageEmbedding_injective

namespace Iut.SourcePacketFiniteMeasuredFieldDecomposition

#print axioms blockFieldDecomposition_image_integralRegion
#print axioms blockIntegralRegion_iff
#print axioms blockRadializedRegion_integralRegion
#print axioms blockRadializedRegion_integralRegion_measurable
#print axioms blockProductMeasure_integralRegion
#print axioms blockVolume_normalizationOffset_eq_zero
#print axioms blockVolume_value_eq_zero
#print axioms packetRadializedRegion_productRegion
#print axioms stageEmbedding_preimage_embeddedPacketIntegralRegion

end Iut.SourcePacketFiniteMeasuredFieldDecomposition

namespace Iut.SourcePacketFiniteStageLogVolume

#print axioms weightChoice_card_factor
#print axioms normalizedReplicaSum_eq_inverseMultiplicitySum
#print axioms weightedLift_productRegion
#print axioms weightedContent_productRegion
#print axioms normalized_log_weightedContent_productRegion
#print axioms toNormalizedLogVolume_valueOn_admissibleProductRegion_eq_weightedSum

namespace Compatible

#print axioms blockRadial_measurePreserving
#print axioms stageKummer_image_packetIntegralRegion
#print axioms packetRadialEquiv_image_radializedRegion
#print axioms replica_measurePreserving
#print axioms replicaEquiv_image_weightedLift
#print axioms weightedContent_image
#print axioms toNormalizedLogVolume_compatible
#print axioms normalizedLogVolume_value_eq
#print axioms packetKummer_image_embeddedPacketIntegralRegion

end Compatible

end Iut.SourcePacketFiniteStageLogVolume

#print axioms Iut.SourcePacketFiniteStageVolume.normalizedLogVolume_value_eq_zero

-- Legacy block-indexed volume lemmas remain visible but are not source endpoints.
#print axioms Iut.SourcePacketLogVolumeDecomposition.algebraicDecomposition
#print axioms Iut.SourcePacketLogVolumeDecomposition.radializedRegion_integralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.productMeasure_radializedIntegralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.weightedLift_integralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.weightedContent_integralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.multiplicity_val
#print axioms Iut.SourcePacketLogVolumeDecomposition.normalizationDenominator_pos
#print axioms Iut.SourcePacketLogVolumeDecomposition.normalizationScale_pos
#print axioms Iut.SourcePacketLogVolumeDecomposition.toNormalizedLogVolume_value
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.radializeCoordinates_coordinateEquiv
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.coordinate_measurePreserving
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.replica_measurePreserving
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.replicaEquiv_image_weightedLift
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.weightedContent_image
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.normalizationOffset_eq
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.toNormalizedLogVolume_compatible
#print axioms Iut.SourceNormalizedLogVolume.Compatible.valueOn_mapRegion
#print axioms Iut.SourceTheorem311VerticalLocalKummer.logVolume_compatible
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transport_logVolume
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.factorTransport_integralLattice_image
#print axioms Iut.SourceNonarchimedeanPacketShells.packetLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalSummandLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFactorLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPureIntegralTensors_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFullNonarchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedNonarchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalSummandSeminorm_compatible
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transportAbove_archimedean_inner
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalSummandInner_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFactorInner_compatible
#print axioms Iut.SourceTensorPacketKummerIso.packetInner_compatible
#print axioms Iut.SourceTensorPacketKummerIso.packetSeminorm_compatible
#print axioms Iut.SourceTensorPacketKummerIso.distinguishedUnitBall_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketInner_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketSeminorm_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFullArchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedArchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFullIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.VerticalPacketIntegralConstruction.logVolumeFunctional_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.VerticalLocalConstruction.toTheorem311VerticalLocalKummer
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.VerticalFamilyConstruction.toTheorem311Ind3System
#print axioms Iut.SourceLGPGaussianLogThetaLattice.monoAnalyticProcession_capsule_card
#print axioms Iut.IUTIIAbsoluteThetaLabel.tensorIndex_zero
#print axioms Iut.IUTIIAbsoluteThetaLabel.tensorIndex_nonzero_pos
#print axioms Iut.IUTIIAbsoluteThetaLabel.tensorIndex_lt_l
#print axioms Iut.SourceArchimedeanIntegralStructure.isClosed_unitBall
#print axioms Iut.SourceArchimedeanIntegralStructure.isClosed_piBall
#print axioms Iut.SourceTheorem311Ind3System.logVolume_eq_common
#print axioms Iut.SourceTheorem311Ind3System.logVolume_eq_logVolume
#print axioms Iut.SourceTheorem311VerticalLogLink.rootsOfUnity_logarithm_eq_zero
#print axioms Iut.SourceTheorem311VerticalLogLink.logarithm_eq_of_differsByRootOfUnity
#print axioms Iut.SourceTheorem311VerticalLogLinkFamily.adjacent_logarithm_eq_on_overlap
#print axioms Iut.SourceTheorem311BadPrimeUpperSemiCompatibility.logarithm_eq_of_relatedAcrossLog
#print axioms Iut.SourceHorizontalKummerCompatibility.commutes
#print axioms Iut.SourceMonoThetaHorizontalKummerCompatibility.automorphismEquiv
#print axioms Iut.SourceTheorem311TwoActionEquivalence.quotientEquiv
#print axioms Iut.SourceTheorem311PermutationBiCoricCompatibility.quotientEquiv
#print axioms Iut.SourceTheorem311HorizontalEvaluationCompatibility.descend_mk
#print axioms Iut.SourceTheorem311IndeterminacyQuotient.sound_ind1
#print axioms Iut.SourceTheorem311IndeterminacyQuotient.sound_ind2
