/-
Copyright (c) 2026 IUT Lean formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: IUT Lean formalization contributors
-/
import Iut.Foundations.SourceHodgeArakelovEvaluation
import Iut.Foundations.SourceTheorem311

open Iut

/-!
# M1-M3 source endpoint axiom audit

This audit keeps the source-faithful Kummer and pointed-restriction endpoints
visible to Lean's axiom reporter.
-/

#print axioms Iut.SourceMLFIntegralMonoid.galoisAction
#print axioms Iut.SourceKummerFaithfulness.eq_one_of_roots_in_profinite
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnity_finite
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rationalCircle_torsion_natCard
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnityEquiv
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnity_natCard
#print axioms Iut.SourceTorsionCyclotomicCommMonoid.rootsOfUnityGroup_natCard
#print axioms Iut.SourceMonoidCyclotome.boundedCoe_isClosedEmbedding
#print axioms Iut.SourceMonoidCyclotome.asProfinite
#print axioms Iut.SourceMonoidCyclotome.eq_one_of_roots
#print axioms Iut.SourceMLFIntegralMonoid.groupificationToAlgebraicClosureUnits_surjective
#print axioms Iut.SourceMLFIntegralMonoid.groupificationEquivAlgebraicClosureUnits
#print axioms Iut.SourceMLFIntegralMonoid.torsionUnit_image
#print axioms Iut.SourceMLFGaloisTMPair.augmentation_surjective
#print axioms Iut.SourceMLFGaloisTMPair.openStabilizer_fixed
#print axioms Iut.SourceMLFGaloisTMPair.continuousCyclotomeAction
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootSystem.ofModel
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootSystem.quotientUnit_exists
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootRealization.ofRootSystem
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootComparison.ofModel
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootTheory.chosen_rootSystem
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootRealization.ratioCyclotome_mul_group
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootRealization.ratioCyclotome_continuous
#print axioms Iut.SourceMLFGaloisTMPair.CompatibleRootComparison.germ_eq
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootTheory.kummerValue_mul
#print axioms Iut.SourceMLFGaloisTMPair.LocalKummerRootTheory.local_toGerm_eq_global
#print axioms Iut.SourceMLFGaloisTMPair.KummerRootTheory.canonicalKummerMap
#print axioms Iut.SourceMLFGaloisTMPair.LocalKummerRootTheory.canonicalKummerMap
#print axioms Iut.SourceMLFGaloisTMPair.LocalKummerRootTheory.canonicalKummerMap_toGerm
#print axioms Iut.SourceIUTIIUnitKummerEmbedding.unitKummer_injective
#print axioms Iut.SourceIUTIIUnitKummerEmbedding.torsionUnitImage_eq_constant_torsion
#print axioms Iut.sourceConstantTorsion_unitKummer
#print axioms Iut.SourceIUTIICorollary112PointedRestriction.detects_constant_torsion
#print axioms Iut.SourceIUTIICorollary112PointedRestriction.splittingUpToTorsion
#print axioms Iut.SourceIUTIIValueProfile.natCard_eq_twoEll_pow_lStar
#print axioms Iut.SourceIUTIIMultiplicativeTorsionAction.actionMap_injective
#print axioms Iut.SourceIUTIIHodgeArakelovThetaPilot.valueProfiles_natCard
#print axioms Iut.SourceIUTIIHodgeArakelovThetaPilot.zeroTheta_carrier_subset_torsion
#print axioms Iut.IUTIIAbsoluteThetaLabel.card_eq_lPlusMinus
#print axioms Iut.SourceIndTopologicalLocalFieldPresentation.transition_id
#print axioms Iut.SourceIndTopologicalLocalFieldPresentation.transition_comp
#print axioms Iut.SourceMonoAnalyticTensorPacket.ind2CoordinateIndex_card
#print axioms Iut.SourceMonoAnalyticTensorPacket.placeTupleIndex_card
#print axioms Iut.SourcePacketFiniteFieldDecomposition.fieldSummandIndex_card
#print axioms Iut.SourceMonoAnalyticTensorPacket.inverse_tprod_mem_distinguishedSubmodule
#print axioms Iut.SourceTheorem311Ind1Action.ofProcessionFunctor_act_apply
#print axioms Iut.CategoryProcession.MemberHom.componentSelf_comp
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.factorTransport_comp
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.TensorTopology.reindexLinearEquiv_trans
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.packetMemberTransport_id
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.packetMemberTransport_comp
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.packetInd1Action
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.localInd1PacketAction
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.LocalConstruction.toLocalInd1Action
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.PresentationConstruction.toInd1Action
#print axioms Iut.SourceDThetaBridgeCore.IsomorphismMember.processionObjectIso
#print axioms Iut.SourceDThetaBridgeCore.IsomorphismMember.monoAnalyticProcessionMemberObjectIso
#print axioms Iut.SourceLGPGaussianLogThetaLattice.verticalCoricityToCommon
#print axioms Iut.SourceTheorem311Ind2SummandAction.factorAction_on_summand
#print axioms Iut.SourceTheorem311Ind2SummandAction.packetAction_mul
#print axioms Iut.SourceTheorem311LocalInd2Action.action_apply
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.ind2ActionAbove_mul
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.localInd2Action
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.LocalConstruction.toLocalInd2Action
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.factorTransport_on_summand
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.TensorTopology.congr_distinguishedSubmodule
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.tensorPacketKummerIso
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketKummerIso
#print axioms Iut.SourceTheorem311LocalData.processionLogVolume
#print axioms Iut.SourceNormalizedLogVolume.PacketNormalization.valueOn_dilateRegion
#print axioms Iut.SourceSelectedPlace.moduliLocalDegree
#print axioms Iut.SourceSelectedPlace.moduliRationalLocalDegree

namespace Iut.SourceTopologicalLocalField.LocalDegreeTower

#print axioms localDegree_eq_relativeDegree_mul_moduliDegree

end Iut.SourceTopologicalLocalField.LocalDegreeTower

namespace Iut.SourcePacketFiniteFieldStage

#print axioms localTensor_finrank
#print axioms field_finrank_sum
#print axioms field_finrank_sum_eq_factor_finrank_product

end Iut.SourcePacketFiniteFieldStage

namespace Iut.SourceNonarchimedeanLocalFieldIntegers

#print axioms normalizedLogVolume_value_eq_zero
#print axioms Iut.ThetaFinitePlace.residueCharacteristic_eq_natGenerator
#print axioms rationalPrime_eq_residueCharacteristic
#print axioms rationalPrime_prime
#print axioms log_rationalPrimeScale
#print axioms localPrimeLogVolumeShift_eq_degree_mul_packetLogVolumeShift
#print axioms rationalPrimeQuotientModule
#print axioms padicScalarMap
#print axioms continuous_padicScalarMap
#print axioms PAdicIntegralBasis.padicPrime_smul
#print axioms PAdicIntegralBasis.coefficientReduction_surjective
#print axioms PAdicIntegralBasis.coefficientReduction_ker
#print axioms PAdicIntegralBasis.quotientLinearEquiv
#print axioms PAdicIntegralBasis.quotient_finrank_eq
#print axioms PAdicIntegralBasis.toRationalPrimeResidueModule
#print axioms RationalPrimeResidueModule.quotientFintype
#print axioms RationalPrimeResidueModule.quotient_card_eq
#print axioms ResidueQuotientFormula.residueCosets_cover_integerRing
#print axioms ResidueQuotientFormula.residueCosets_pairwiseDisjoint
#print axioms ResidueQuotientFormula.scaledRing_measure_eq_scale
#print axioms ResidueQuotientFormula.toHaarDegreeFormula
#print axioms normalizedHaarMeasure_rationalPrimeDilation
#print axioms normalizedLogVolume_admissible_rationalPrimeDilation
#print axioms normalizedLogVolume_rawLogVolume_rationalPrimeDilation
#print axioms normalizedLogVolume_valueOn_rationalPrimeDilation

end Iut.SourceNonarchimedeanLocalFieldIntegers

#print axioms Iut.SourcePacketMeasuredField.NonarchimedeanPrimeDilation.ofIntegers

namespace Iut.SourcePacketFiniteMeasuredFieldDecomposition

#print axioms blockFieldDecomposition_image_blockFieldProductRegion
#print axioms blockRadializedRegion_blockFieldProductRegion
#print axioms blockProductMeasure_blockFieldProductRegion
#print axioms blockVolume_valueOn_blockFieldProductAdmissibleRegion

end Iut.SourcePacketFiniteMeasuredFieldDecomposition

namespace Iut.SourcePacketFiniteStageLogVolume.DirectProductPrimeNormalization

#print axioms factor_localDegree
#print axioms block_degree_sum
#print axioms blockDilation_image_blockFieldProductRegion
#print axioms blockVolume_valueOn_dilatedFieldRegions_eq_degreeProduct
#print axioms stageDilation_image_packetAdmissibleRegion
#print axioms valueOn_dilatedPacketAdmissibleRegion

end Iut.SourcePacketFiniteStageLogVolume.DirectProductPrimeNormalization

#print axioms Iut.SourcePacketMeasuredField.ofNonarchimedean
#print axioms Iut.SourceArchimedeanLocalFieldModel.complexNorm_image_integralRegion
#print axioms Iut.SourceArchimedeanLocalFieldModel.radialLengthMeasure_unitRadialInterval
#print axioms Iut.SourceArchimedeanLocalFieldModel.completedRadialLengthMeasure_image_integralRegion
#print axioms Iut.SourceArchimedeanLocalFieldModel.normalizedLogVolume_value_eq_zero
#print axioms Iut.SourceArchimedeanLocalFieldModel.addCircleVolume_image_of_injOn
#print axioms Iut.SourceArchimedeanLocalFieldModel.angularLengthMeasure_univ
#print axioms Iut.SourceArchimedeanLocalFieldModel.angularLengthMeasure_mul_image
#print axioms Iut.SourceArchimedeanLocalFieldModel.continuous_complexAngularProjection

namespace Iut.SourceArchimedeanLocalFieldModel.AngularRegion

#print axioms angularVolume_pos
#print axioms angularVolume_lt_top
#print axioms angularVolume_mulLeft
#print axioms angularLogVolume_mulLeft

end Iut.SourceArchimedeanLocalFieldModel.AngularRegion

namespace Iut.SourceArchimedeanLocalFieldModel.ExponentialRegion

#print axioms angularLengthMeasure_angularImage
#print axioms completedRadialLengthMeasure_fieldCarrier_eq_angular
#print axioms normalizedLogVolume_valueOn_eq_angularLogVolume

end Iut.SourceArchimedeanLocalFieldModel.ExponentialRegion

#print axioms Iut.SourceArchimedeanLocalFieldModel.radialLengthMeasure_packetScale
#print axioms Iut.SourceArchimedeanLocalFieldModel.radialization_image_packetDilation
#print axioms Iut.SourceArchimedeanLocalFieldModel.completedRadialLengthMeasure_packetDilation
#print axioms Iut.SourceArchimedeanLocalFieldModel.packetNormalization
#print axioms Iut.SourcePacketMeasuredField.ofArchimedean
#print axioms Iut.SourcePacketMeasuredField.integral_measure_eq_one
#print axioms Iut.SourcePacketMeasuredField.normalizationOffset_eq_zero
#print axioms SourcePacketFiniteFieldDecomposition.stageEmbedding_injective

namespace Iut.SourcePacketFiniteMeasuredFieldDecomposition

#print axioms blockFieldDecomposition_image_integralRegion
#print axioms blockIntegralRegion_iff
#print axioms blockRadializedRegion_integralRegion
#print axioms blockRadializedRegion_integralRegion_measurable
#print axioms blockProductMeasure_integralRegion
#print axioms blockVolume_normalizationOffset_eq_zero
#print axioms blockVolume_value_eq_zero
#print axioms packetRadializedRegion_productRegion
#print axioms stageEmbedding_preimage_embeddedPacketIntegralRegion

end Iut.SourcePacketFiniteMeasuredFieldDecomposition

namespace Iut.SourcePacketFiniteStageLogVolume

#print axioms weightChoice_card_factor
#print axioms normalizedReplicaSum_eq_inverseMultiplicitySum
#print axioms weightedLift_productRegion
#print axioms weightedContent_productRegion
#print axioms normalized_log_weightedContent_productRegion
#print axioms toNormalizedLogVolume_valueOn_admissibleProductRegion_eq_weightedSum

namespace Compatible

#print axioms blockRadial_measurePreserving
#print axioms stageKummer_image_packetIntegralRegion
#print axioms packetRadialEquiv_image_radializedRegion
#print axioms replica_measurePreserving
#print axioms replicaEquiv_image_weightedLift
#print axioms weightedContent_image
#print axioms toNormalizedLogVolume_compatible
#print axioms normalizedLogVolume_value_eq
#print axioms packetKummer_image_embeddedPacketIntegralRegion

end Compatible

end Iut.SourcePacketFiniteStageLogVolume

#print axioms Iut.SourcePacketFiniteStageVolume.normalizedLogVolume_value_eq_zero

-- Legacy block-indexed volume lemmas remain visible but are not source endpoints.
#print axioms Iut.SourcePacketLogVolumeDecomposition.algebraicDecomposition
#print axioms Iut.SourcePacketLogVolumeDecomposition.radializedRegion_integralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.productMeasure_radializedIntegralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.weightedLift_integralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.weightedContent_integralRegion
#print axioms Iut.SourcePacketLogVolumeDecomposition.multiplicity_val
#print axioms Iut.SourcePacketLogVolumeDecomposition.normalizationDenominator_pos
#print axioms Iut.SourcePacketLogVolumeDecomposition.normalizationScale_pos
#print axioms Iut.SourcePacketLogVolumeDecomposition.toNormalizedLogVolume_value
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.radializeCoordinates_coordinateEquiv
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.coordinate_measurePreserving
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.replica_measurePreserving
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.replicaEquiv_image_weightedLift
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.weightedContent_image
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.normalizationOffset_eq
#print axioms Iut.SourcePacketLogVolumeDecomposition.Compatible.toNormalizedLogVolume_compatible
#print axioms Iut.SourceNormalizedLogVolume.Compatible.valueOn_mapRegion
#print axioms Iut.SourceTheorem311VerticalLocalKummer.logVolume_compatible
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transport_logVolume
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.factorTransport_integralLattice_image
#print axioms Iut.SourceNonarchimedeanPacketShells.packetLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalSummandLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFactorLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPureIntegralTensors_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedLattice_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFullNonarchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedNonarchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalSummandSeminorm_compatible
#print axioms Iut.SourceMonoAnalyticLogShellAlgorithm.transportAbove_archimedean_inner
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalSummandInner_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFactorInner_compatible
#print axioms Iut.SourceTensorPacketKummerIso.packetInner_compatible
#print axioms Iut.SourceTensorPacketKummerIso.packetSeminorm_compatible
#print axioms Iut.SourceTensorPacketKummerIso.distinguishedUnitBall_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketInner_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalPacketSeminorm_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFullArchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedArchimedeanIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalFullIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.verticalDistinguishedIntegral_image
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.VerticalPacketIntegralConstruction.logVolumeFunctional_compatible
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.VerticalLocalConstruction.toTheorem311VerticalLocalKummer
#print axioms Iut.SourceAbsoluteLGPGaussianLogThetaLattice.VerticalFamilyConstruction.toTheorem311Ind3System
#print axioms Iut.SourceLGPGaussianLogThetaLattice.monoAnalyticProcession_capsule_card
#print axioms Iut.IUTIIAbsoluteThetaLabel.tensorIndex_zero
#print axioms Iut.IUTIIAbsoluteThetaLabel.tensorIndex_nonzero_pos
#print axioms Iut.IUTIIAbsoluteThetaLabel.tensorIndex_lt_l
#print axioms Iut.SourceArchimedeanIntegralStructure.isClosed_unitBall
#print axioms Iut.SourceArchimedeanIntegralStructure.isClosed_piBall
#print axioms Iut.SourceTheorem311Ind3System.logVolume_eq_common
#print axioms Iut.SourceTheorem311Ind3System.logVolume_eq_logVolume
#print axioms Iut.SourceTheorem311VerticalLogLink.rootsOfUnity_logarithm_eq_zero
#print axioms Iut.SourceTheorem311VerticalLogLink.logarithm_eq_of_differsByRootOfUnity
#print axioms Iut.SourceTheorem311VerticalLogLinkFamily.adjacent_logarithm_eq_on_overlap
#print axioms Iut.SourceTheorem311BadPrimeUpperSemiCompatibility.logarithm_eq_of_relatedAcrossLog
#print axioms Iut.SourceHorizontalKummerCompatibility.commutes
#print axioms Iut.SourceMonoThetaHorizontalKummerCompatibility.automorphismEquiv
#print axioms Iut.SourceTheorem311TwoActionEquivalence.quotientEquiv
#print axioms Iut.SourceTheorem311PermutationBiCoricCompatibility.quotientEquiv
#print axioms Iut.SourceTheorem311HorizontalEvaluationCompatibility.descend_mk
#print axioms Iut.SourceTheorem311IndeterminacyQuotient.sound_ind1
#print axioms Iut.SourceTheorem311IndeterminacyQuotient.sound_ind2
