/-
Copyright (c) 2026 IUT Lean formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: IUT Lean formalization contributors
-/
import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Algebra.Group.TypeTags.Finite
import Mathlib.Algebra.Group.ULift
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Basic

/-!
# Group-theoretic quotients from Etale Theta, Section 2

This file formalizes the algebraic part of the construction preceding
`Etale Theta`, Definition 2.1. It does not assert that these quotients have
already been realized by finite etale covers of an orbicurve.
-/

open Function

namespace Iut.EtaleTheta

universe u

section LowerCentral

variable (G : Type u) [Group G]

/-- The commutator subgroup `[G,G]`. -/
abbrev derivedSubgroup : Subgroup G :=
  commutator G

/-- The third term `[G,[G,G]]` of the lower central series. -/
def thetaCommutatorKernel : Subgroup G :=
  ⁅(⊤ : Subgroup G), derivedSubgroup G⁆

instance thetaCommutatorKernel_normal :
    (thetaCommutatorKernel G).Normal := by
  change ⁅(⊤ : Subgroup G), commutator G⁆.Normal
  infer_instance

/-- The two-step nilpotent theta quotient `G/[G,[G,G]]`. -/
abbrev ThetaQuotient :=
  G ⧸ thetaCommutatorKernel G

/-- The elliptic abelianization `G/[G,G]`. -/
abbrev EllipticAbelianization :=
  G ⧸ derivedSubgroup G

theorem thetaCommutatorKernel_le_derivedSubgroup :
    thetaCommutatorKernel G ≤ derivedSubgroup G :=
  Subgroup.commutator_le_right _ _

/-- The canonical projection from the theta quotient to the abelianization. -/
def thetaToElliptic :
    ThetaQuotient G →* EllipticAbelianization G :=
  QuotientGroup.map
    (thetaCommutatorKernel G)
    (derivedSubgroup G)
    (MonoidHom.id G)
    (thetaCommutatorKernel_le_derivedSubgroup G)

theorem thetaToElliptic_mk (g : G) :
    thetaToElliptic G (QuotientGroup.mk g) = QuotientGroup.mk g :=
  rfl

/-- The normal subgroup generated by the `l`-th powers in the theta quotient. -/
def lPowerKernel (l : ℕ) : Subgroup (ThetaQuotient G) :=
  Subgroup.normalClosure {x | ∃ y : ThetaQuotient G, x = y ^ l}

instance lPowerKernel_normal (l : ℕ) :
    (lPowerKernel G l).Normal :=
  Subgroup.normalClosure_normal

/-- The exponent-`l` theta quotient used in the construction before Definition 2.1. -/
abbrev ModLThetaQuotient (l : ℕ) :=
  ThetaQuotient G ⧸ lPowerKernel G l

/-- The canonical projection from the geometric fundamental group. -/
def modLThetaProjection (l : ℕ) :
    G →* ModLThetaQuotient G l :=
  (QuotientGroup.mk' (lPowerKernel G l)).comp
    (QuotientGroup.mk' (thetaCommutatorKernel G))

theorem modLThetaProjection_surjective (l : ℕ) :
    Surjective (modLThetaProjection G l) :=
  (QuotientGroup.mk'_surjective _).comp
    (QuotientGroup.mk'_surjective _)

theorem lth_power_maps_to_one (l : ℕ) (x : ThetaQuotient G) :
    QuotientGroup.mk (x ^ l) = (1 : ModLThetaQuotient G l) := by
  apply (QuotientGroup.eq_one_iff (x ^ l)).mpr
  exact Subgroup.subset_normalClosure ⟨x, rfl⟩

/-- The normal subgroup generated by `l`-th powers in the elliptic abelianization. -/
def ellipticLPowerKernel (l : ℕ) : Subgroup (EllipticAbelianization G) :=
  Subgroup.normalClosure
    {x | ∃ y : EllipticAbelianization G, x = y ^ l}

instance ellipticLPowerKernel_normal (l : ℕ) :
    (ellipticLPowerKernel G l).Normal :=
  Subgroup.normalClosure_normal

/--
The mod-`l` elliptic quotient. For a once-punctured elliptic curve this is the
rank-two module `(Z/lZ)^2` denoted `Delta_X^ell` in Etale Theta, Section 2.
-/
abbrev ModLEllipticAbelianization (l : ℕ) :=
  EllipticAbelianization G ⧸ ellipticLPowerKernel G l

/-- The canonical projection from a group to its mod-`l` abelianization. -/
def modLEllipticProjection (l : ℕ) :
    G →* ModLEllipticAbelianization G l :=
  (QuotientGroup.mk' (ellipticLPowerKernel G l)).comp
    (QuotientGroup.mk' (derivedSubgroup G))

theorem modLEllipticProjection_surjective (l : ℕ) :
    Surjective (modLEllipticProjection G l) :=
  (QuotientGroup.mk'_surjective _).comp
    (QuotientGroup.mk'_surjective _)

theorem thetaToElliptic_maps_lPowerKernel (l : ℕ) :
    lPowerKernel G l ≤
      (ellipticLPowerKernel G l).comap (thetaToElliptic G) := by
  apply Subgroup.normalClosure_le_normal
  rintro x ⟨y, rfl⟩
  change thetaToElliptic G (y ^ l) ∈ ellipticLPowerKernel G l
  rw [map_pow]
  exact Subgroup.subset_normalClosure
    ⟨thetaToElliptic G y, rfl⟩

/--
The canonical surjection
`Delta_X^Theta/l-powers -> Delta_X^ell/l-powers`.
-/
def modLThetaToElliptic (l : ℕ) :
    ModLThetaQuotient G l →* ModLEllipticAbelianization G l :=
  QuotientGroup.map
    (lPowerKernel G l)
    (ellipticLPowerKernel G l)
    (thetaToElliptic G)
    (thetaToElliptic_maps_lPowerKernel G l)

@[simp]
theorem modLThetaToElliptic_mk (l : ℕ) (x : ThetaQuotient G) :
    modLThetaToElliptic G l (QuotientGroup.mk x) =
      QuotientGroup.mk (thetaToElliptic G x) :=
  rfl

theorem thetaToElliptic_surjective :
    Surjective (thetaToElliptic G) := by
  intro x
  refine QuotientGroup.induction_on x ?_
  intro g
  exact ⟨QuotientGroup.mk g, rfl⟩

theorem modLThetaToElliptic_surjective (l : ℕ) :
    Surjective (modLThetaToElliptic G l) := by
  intro x
  refine QuotientGroup.induction_on x ?_
  intro y
  obtain ⟨z, rfl⟩ := thetaToElliptic_surjective G y
  exact ⟨QuotientGroup.mk z, rfl⟩

/--
The central theta direction `Delta^Theta`, defined as the kernel of the
canonical map to the mod-`l` elliptic quotient.
-/
def ModLThetaCenter (l : ℕ) :
    Subgroup (ModLThetaQuotient G l) :=
  (modLThetaToElliptic G l).ker

instance modLThetaCenter_normal (l : ℕ) :
    (ModLThetaCenter G l).Normal := by
  change (modLThetaToElliptic G l).ker.Normal
  infer_instance

/-- The quotient by the theta center is the mod-`l` elliptic quotient. -/
noncomputable def modLThetaQuotientByCenterEquiv (l : ℕ) :
    ModLThetaQuotient G l ⧸ ModLThetaCenter G l ≃*
      ModLEllipticAbelianization G l :=
  QuotientGroup.quotientKerEquivOfSurjective
    (modLThetaToElliptic G l)
    (modLThetaToElliptic_surjective G l)

end LowerCentral

section Lagrangian

/-- The multiplicative presentation of the additive rank-one module `Z/lZ`. -/
abbrev LTorsionLabel (l : ℕ) :=
  Multiplicative (ZMod l)

/-- A universe lift of the finite `Z/lZ` label group. -/
abbrev LiftedLTorsionLabel (l : ℕ) :=
  ULift.{u} (LTorsionLabel l)

/--
The source rank assertions for the lower-central quotient of the geometric
fundamental group of a once-punctured elliptic curve.

The quotient groups are derived above. These equivalences record the genuinely
geometric input that the theta center has rank one and the elliptic quotient
has rank two over `Z/lZ`; they are not inferred from cardinalities.
-/
structure OncePuncturedEllipticThetaRealization
    (l : ℕ) (Delta : Type u) [Group Delta] where
  thetaCenter :
    ModLThetaCenter Delta l ≃*
      LTorsionLabel l
  ellipticDirections :
    ModLEllipticAbelianization Delta l ≃*
      LTorsionLabel l × LTorsionLabel l

namespace OncePuncturedEllipticThetaRealization

variable {l : ℕ} {Delta : Type u} [Group Delta]

theorem thetaCenter_rankOne
    (realization : OncePuncturedEllipticThetaRealization l Delta) :
    Nonempty
      (ModLThetaCenter Delta l ≃*
        LTorsionLabel l) :=
  ⟨OncePuncturedEllipticThetaRealization.thetaCenter realization⟩

theorem ellipticDirections_rankTwo
    (realization : OncePuncturedEllipticThetaRealization l Delta) :
    Nonempty
      (ModLEllipticAbelianization Delta l ≃*
        LTorsionLabel l × LTorsionLabel l) :=
  ⟨OncePuncturedEllipticThetaRealization.ellipticDirections realization⟩

end OncePuncturedEllipticThetaRealization

/-- Remove the universe lift from an `l`-torsion label. -/
def liftedLTorsionEquiv (l : ℕ) :
    LiftedLTorsionLabel.{u} l ≃* LTorsionLabel l :=
  MulEquiv.ulift

/-- The finite discrete profinite group underlying the rank-one module `Z/lZ`. -/
def lTorsionProfiniteGroup (l : ℕ) [NeZero l] : ProfiniteGrp.{u} :=
  ProfiniteGrp.ofFiniteGrp (FiniteGrp.of (LiftedLTorsionLabel.{u} l))

/--
The precise group-theoretic input called a quotient `Pi_X^ell -> Q` in the
construction preceding Etale Theta, Definition 2.1.

The quotient is onto a rank-one `Z/lZ`; its restriction to the geometric
subgroup remains onto, while it is trivial on the cuspidal decomposition group.
-/
structure LagrangianQuotient
    (l : ℕ) (Pi : Type u) [Group Pi] where
  geometricSubgroup : Subgroup Pi
  cuspDecompositionGroup : Subgroup Pi
  quotient : Pi →* LTorsionLabel l
  quotient_surjective : Surjective quotient
  geometric_surjective :
    Surjective (quotient.comp geometricSubgroup.subtype)
  cusp_trivial :
    cuspDecompositionGroup ≤ quotient.ker

namespace LagrangianQuotient

variable {l : ℕ} {Pi : Type u} [Group Pi]
variable (Q : LagrangianQuotient l Pi)

/-- The normal open-subgroup candidate corresponding to the `Q`-cover. -/
def coverSubgroup : Subgroup Pi :=
  Q.quotient.ker

instance coverSubgroup_normal :
    Q.coverSubgroup.Normal := by
  change Q.quotient.ker.Normal
  infer_instance

/-- The first-isomorphism-theorem identification `Pi/ker(Q) = Z/lZ`. -/
noncomputable def coverQuotientEquiv :
    Pi ⧸ Q.coverSubgroup ≃* LTorsionLabel l :=
  QuotientGroup.quotientKerEquivOfSurjective
    Q.quotient Q.quotient_surjective

theorem cuspDecompositionGroup_le_coverSubgroup :
    Q.cuspDecompositionGroup ≤ Q.coverSubgroup :=
  Q.cusp_trivial

theorem geometricRestriction_surjective :
    Surjective (Q.quotient.comp Q.geometricSubgroup.subtype) :=
  Q.geometric_surjective

end LagrangianQuotient

/--
The topological refinement of a Lagrangian quotient: a continuous surjection
from a profinite arithmetic group onto the finite discrete group `Z/lZ`.
-/
structure ProfiniteLagrangianQuotient
    (l : ℕ) [NeZero l] (Pi : ProfiniteGrp.{u}) where
  geometricSubgroup : Subgroup Pi
  cuspDecompositionGroup : Subgroup Pi
  quotient : Pi ⟶ lTorsionProfiniteGroup l
  quotient_surjective : Surjective quotient
  geometric_surjective :
    Surjective
      ((liftedLTorsionEquiv l).toMonoidHom.comp
        (quotient.hom.toMonoidHom.comp geometricSubgroup.subtype))
  cusp_trivial :
    cuspDecompositionGroup ≤ quotient.hom.ker

namespace ProfiniteLagrangianQuotient

variable {l : ℕ} [NeZero l] {Pi : ProfiniteGrp.{u}}
variable (Q : ProfiniteLagrangianQuotient l Pi)

/-- The underlying quotient homomorphism after removing the universe lift. -/
def underlyingQuotient :
    Pi →* LTorsionLabel l :=
  (liftedLTorsionEquiv l).toMonoidHom.comp Q.quotient.hom.toMonoidHom

/-- Forgetting topology recovers the algebraic Lagrangian quotient. -/
def toLagrangianQuotient :
    LagrangianQuotient l Pi where
  geometricSubgroup := Q.geometricSubgroup
  cuspDecompositionGroup := Q.cuspDecompositionGroup
  quotient := Q.underlyingQuotient
  quotient_surjective :=
    (liftedLTorsionEquiv l).surjective.comp Q.quotient_surjective
  geometric_surjective := Q.geometric_surjective
  cusp_trivial := by
    intro x hx
    change Q.underlyingQuotient x = 1
    have hq : Q.quotient x = 1 := Q.cusp_trivial hx
    exact (liftedLTorsionEquiv l).map_eq_one_iff.mpr hq

/-- The kernel subgroup corresponding to the finite profinite cover. -/
def coverSubgroup : Subgroup Pi :=
  Q.underlyingQuotient.ker

instance coverSubgroup_normal :
    Q.coverSubgroup.Normal := by
  change Q.underlyingQuotient.ker.Normal
  infer_instance

theorem coverSubgroup_isOpen :
    IsOpen ((Q.coverSubgroup : Subgroup Pi) : Set Pi) := by
  have hset :
      {x : Pi | Q.underlyingQuotient x = 1} =
        {x : Pi | Q.quotient x = 1} := by
    ext x
    change
      (liftedLTorsionEquiv l) (Q.quotient x) = 1 ↔
        Q.quotient x = 1
    exact (liftedLTorsionEquiv l).map_eq_one_iff
  change IsOpen {x : Pi | Q.underlyingQuotient x = 1}
  rw [hset]
  have hopen :
      IsOpen ({1} : Set (lTorsionProfiniteGroup l)) := by
    change @IsOpen (LiftedLTorsionLabel.{u} l) ⊥ {1}
    letI : TopologicalSpace (LiftedLTorsionLabel.{u} l) := ⊥
    letI : DiscreteTopology (LiftedLTorsionLabel.{u} l) := ⟨rfl⟩
    exact isOpen_discrete _
  exact hopen.preimage Q.quotient.hom.continuous

/-- The quotient kernel is an actual open embedding into the arithmetic group. -/
def coverOpenEmbedding :
    Topology.IsOpenEmbedding
      (Q.coverSubgroup.subtype : Q.coverSubgroup → Pi) :=
  Q.coverSubgroup_isOpen.isOpenEmbedding_subtypeVal

/-- The first-isomorphism theorem for the continuous finite quotient. -/
noncomputable def coverQuotientEquiv :
    Pi ⧸ Q.coverSubgroup ≃* LTorsionLabel l :=
  Q.toLagrangianQuotient.coverQuotientEquiv

end ProfiniteLagrangianQuotient

/-- An actual order-two automorphism of the arithmetic group lifting elliptic inversion. -/
structure InversionAction (Pi : Type u) [Group Pi] where
  automorphism : Pi ≃* Pi
  involutive : automorphism.trans automorphism = MulEquiv.refl Pi

namespace InversionAction

variable {Pi : Type u} [Group Pi]
variable (inversion : InversionAction Pi)

theorem apply_apply (g : Pi) :
    inversion.automorphism (inversion.automorphism g) = g := by
  have h := DFunLike.congr_fun inversion.involutive g
  simpa using h

end InversionAction

/--
Compatibility of inversion with a Lagrangian quotient: the induced action on
`Q = Z/lZ` is multiplication by `-1`.
-/
structure InversionCompatibleLagrangian
    (l : ℕ) (Pi : Type u) [Group Pi]
    (Q : LagrangianQuotient l Pi)
    (inversion : InversionAction Pi) where
  quotient_inversion :
    ∀ g : Pi, Q.quotient (inversion.automorphism g) = (Q.quotient g)⁻¹

namespace InversionCompatibleLagrangian

variable {l : ℕ} {Pi : Type u} [Group Pi]
variable {Q : LagrangianQuotient l Pi}
variable {inversion : InversionAction Pi}
theorem coverSubgroup_invariant
    (compatibility : InversionCompatibleLagrangian l Pi Q inversion)
    {g : Pi} (hg : g ∈ Q.coverSubgroup) :
    inversion.automorphism g ∈ Q.coverSubgroup := by
  rw [LagrangianQuotient.coverSubgroup, MonoidHom.mem_ker] at hg ⊢
  rw [InversionCompatibleLagrangian.quotient_inversion compatibility, hg, inv_one]

end InversionCompatibleLagrangian

end Lagrangian

section SignLabels

variable {Q : Type u} [CommGroup Q]

/-- The nonidentity elements of a pointed multiplicative quotient `Q`. -/
abbrev NonzeroLabel (Q : Type u) [CommGroup Q] :=
  {x : Q // x ≠ 1}

namespace NonzeroLabel

instance : Inv (NonzeroLabel Q) where
  inv x :=
    ⟨x.1⁻¹, fun h => x.2 (inv_eq_one.mp h)⟩

@[simp]
theorem val_inv (x : NonzeroLabel Q) :
    ((x⁻¹ : NonzeroLabel Q) : Q) = (x : Q)⁻¹ :=
  rfl

@[simp]
theorem inv_inv (x : NonzeroLabel Q) :
    x⁻¹⁻¹ = x := by
  apply Subtype.ext
  simp

end NonzeroLabel

/-- The relation identifying a nonzero label with its inverse. -/
def signRel (x y : NonzeroLabel Q) : Prop :=
  x = y ∨ x = y⁻¹

theorem signRel_refl (x : NonzeroLabel Q) :
    signRel x x :=
  Or.inl rfl

theorem signRel_symm {x y : NonzeroLabel Q} :
    signRel x y → signRel y x := by
  rintro (h | h)
  · exact Or.inl h.symm
  · exact Or.inr (by simp [h])

theorem signRel_trans {x y z : NonzeroLabel Q} :
    signRel x y → signRel y z → signRel x z := by
  rintro (hxy | hxy) (hyz | hyz)
  · exact Or.inl (hxy.trans hyz)
  · exact Or.inr (hxy.trans hyz)
  · exact Or.inr (hxy.trans (congrArg Inv.inv hyz))
  · exact Or.inl (hxy.trans (congrArg Inv.inv hyz) |>.trans (NonzeroLabel.inv_inv z))

/-- The sign-orbit set `(Q \ {1})/{q ~ q^-1}` used to label quotient cusps. -/
def signSetoid (Q : Type u) [CommGroup Q] : Setoid (NonzeroLabel Q) where
  r := signRel
  iseqv := ⟨signRel_refl, signRel_symm, signRel_trans⟩

/-- Nonzero `Q`-labels modulo the involution induced by elliptic inversion. -/
abbrev SignLabel (Q : Type u) [CommGroup Q] :=
  Quotient (signSetoid Q)

def toSignLabel (x : NonzeroLabel Q) : SignLabel Q :=
  Quotient.mk (signSetoid Q) x

theorem toSignLabel_inv (x : NonzeroLabel Q) :
    toSignLabel x⁻¹ = toSignLabel x :=
  Quotient.sound (Or.inr rfl)

end SignLabels

end Iut.EtaleTheta
