/-
Copyright (c) 2026 IUT Lean formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: IUT Lean formalization contributors
-/
import Iut.Foundations.SourceDefinition52IndSystem
import Mathlib.Analysis.Normed.Field.Dense
import Mathlib.LinearAlgebra.Countable

/-!
# Sequential finite-place stages for IUT I, Definition 5.2(v)

This file proves the arithmetic input needed to replace the filtered system of
all finite Galois subextensions of a number-field completion by a cofinal
sequence.  The proof follows the standard local-field argument: the global
number field is dense in its completion, primitive elements are approximated
by roots of global polynomials, and Krasner's lemma preserves the generated
local extension.
-/

namespace Iut

universe u

set_option synthInstance.maxHeartbeats 400000 in
-- Scalar towers through the completed field and its algebraic closure require
-- deeper typeclass search in the finite-stage dimension arguments below.
section

namespace SourceFinitePlaceReconstruction

noncomputable section

variable {K : Type u} [Field K] [NumberField K]

/-- The canonical number-field embedding into its completion has dense range. -/
theorem denseRange_algebraMap_base
    (place : NumberField.FinitePlace K) :
    DenseRange (algebraMap K (Base place)) := by
  exact
    IsDedekindDomain.HeightOneSpectrum.denseRange_algebraMap K
      (ThetaFinitePlace.underlyingPrime place)

/-- Every finite Galois stage is generated by one element inside the fixed
algebraic closure. -/
theorem exists_stage_primitive_generator
    (place : NumberField.FinitePlace K) (stage : StageIndex place) :
    ∃ generator : Closure place,
      IntermediateField.adjoin (Base place) {generator} =
        stage.toIntermediateField := by
  obtain ⟨generator, generator_primitive⟩ :=
    Field.exists_primitive_element (Base place) stage
  refine ⟨(generator : Closure place), ?_⟩
  apply IntermediateField.eq_of_le_of_finrank_eq
    (IntermediateField.adjoin_simple_le_iff.mpr generator.2)
  calc
    Module.finrank (Base place)
        (IntermediateField.adjoin (Base place) {(generator : Closure place)}) =
        (minpoly (Base place) (generator : Closure place)).natDegree :=
      IntermediateField.adjoin.finrank
        (Algebra.IsAlgebraic.isAlgebraic
          (generator : Closure place)).isIntegral
    _ = (minpoly (Base place) generator).natDegree := by
      exact congrArg Polynomial.natDegree
        (minpoly.algHom_eq stage.toIntermediateField.val
          stage.toIntermediateField.val.injective generator)
    _ = Module.finrank (Base place)
        (IntermediateField.adjoin (Base place) {generator}) :=
      (IntermediateField.adjoin.finrank
        (IsIntegral.of_finite (Base place) generator)).symm
    _ = Module.finrank (Base place) stage := by
      rw [generator_primitive]
      exact IntermediateField.finrank_top'

/-- A local algebraic generator can be replaced by a root of a polynomial
over the dense global number field without changing the generated local
extension.  This is the Krasner step in the countability argument. -/
theorem exists_global_polynomial_root_same_adjoin
    (place : NumberField.FinitePlace K) (generator : Closure place) :
    ∃ globalPolynomial : Polynomial K, ∃ root : Closure place,
      root ∈
          (globalPolynomial.map (algebraMap K (Base place))).rootSet
            (Closure place) ∧
        IntermediateField.adjoin (Base place) {generator} =
          IntermediateField.adjoin (Base place) {root} := by
  classical
  let f : Polynomial (Base place) := minpoly (Base place) generator
  have generatorIntegral : IsIntegral (Base place) generator :=
    (Algebra.IsAlgebraic.isAlgebraic generator).isIntegral
  have fMonic : f.Monic := minpoly.monic generatorIntegral
  have fAtGenerator : f.aeval generator = 0 := minpoly.aeval _ _
  have fNatDegreeNeZero : f.natDegree ≠ 0 :=
    (minpoly.natDegree_pos generatorIntegral).ne'
  let conjugates : Finset (Closure place) :=
    {root ∈ (f.rootSet (Closure place)).toFinset | root ≠ generator}
  let separation : ℝ :=
    if nonempty : conjugates.Nonempty then
      Finset.min' (conjugates.image fun root => ‖generator - root‖)
        (Finset.image_nonempty.mpr nonempty)
    else 1
  have separation_le_conjugate :
      ∀ conjugate : Closure place,
        IsConjRoot (Base place) generator conjugate →
          generator ≠ conjugate →
            separation ≤ ‖generator - conjugate‖ := by
    intro conjugate conjugateRoot distinct
    by_cases nonempty : conjugates.Nonempty
    · simp only [nonempty, ↓reduceDIte, separation]
      apply Finset.min'_le
        (conjugates.image fun root => ‖generator - root‖)
        ‖generator - conjugate‖
      apply Finset.mem_image_of_mem
      simp only [Finset.mem_filter, Set.mem_toFinset, conjugates]
      exact
        ⟨(isConjRoot_iff_mem_minpoly_rootSet generatorIntegral).mp
            conjugateRoot,
          distinct.symm⟩
    · simp only [nonempty, ↓reduceDIte, separation]
      simp only [Finset.not_nonempty_iff_eq_empty,
        Finset.filter_eq_empty_iff, Set.mem_toFinset, not_not,
        conjugates] at nonempty
      exact
        (distinct
          (nonempty
            ((isConjRoot_iff_mem_minpoly_rootSet generatorIntegral).mp
              conjugateRoot)).symm).elim
  have separationPositive : separation > 0 := by
    by_cases nonempty : conjugates.Nonempty
    · simp only [nonempty, ↓reduceDIte, separation]
      simp only [gt_iff_lt, Finset.lt_min'_iff, Finset.mem_image,
        forall_exists_index, and_imp, forall_apply_eq_imp_iff₂]
      rintro conjugate conjugateMem
      simp only [Finset.mem_filter, Set.mem_toFinset, conjugates] at conjugateMem
      rw [norm_pos_iff, sub_ne_zero]
      exact conjugateMem.2.symm
    · simp only [nonempty, ↓reduceDIte, separation]
      linarith
  have approximationPositive :
      (separation / max ‖generator‖ 1) ^ f.natDegree /
          (f.natDegree + 1) > 0 := by
    positivity
  obtain ⟨globalPolynomial, globalMonic, sameDegree, coefficientsClose⟩ :=
    Polynomial.exists_monic_and_natDegree_eq_and_norm_map_algebraMap_coeff_sub_lt
      (denseRange_algebraMap_base place) fMonic approximationPositive
  let localPolynomial : Polynomial (Base place) :=
    globalPolynomial.map (algebraMap K (Base place))
  have localMonic : localPolynomial.Monic := globalMonic.map _
  obtain ⟨root, rootOfLocalPolynomial, generatorRootClose⟩ :=
    Polynomial.exists_aroots_norm_sub_lt_of_norm_coeff_sub_lt
      approximationPositive fAtGenerator fMonic localMonic
      (sameDegree ▸ globalPolynomial.natDegree_map _)
      coefficientsClose (IsAlgClosed.splits _)
  have generatorRootClose : ‖generator - root‖ < separation := by
    rw [← Real.rpow_natCast, ← mul_comm_div, div_self, one_mul,
      ← Real.rpow_mul
        (div_pos separationPositive (by positivity)).le,
      mul_inv_cancel₀] at generatorRootClose
    · simpa [mul_assoc,
        div_mul_cancel₀ _ (by positivity : max ‖generator‖ 1 > 0).ne']
        using generatorRootClose
    · simp [fNatDegreeNeZero]
    · positivity
  have rootIntegral : IsIntegral (Base place) root :=
    ⟨localPolynomial, localMonic,
      (Polynomial.mem_aroots.mp rootOfLocalPolynomial).2⟩
  have generatorMemRootAdjoin :
      generator ∈ IntermediateField.adjoin (Base place) {root} := by
    exact
      IsKrasner.krasner
        (minpoly.irreducible generatorIntegral).separable
        (IsAlgClosed.splits _)
        rootIntegral
        (fun conjugate conjugateRoot distinct =>
          lt_of_lt_of_le generatorRootClose
            (separation_le_conjugate conjugate conjugateRoot distinct))
  have generatorAdjoinLeRootAdjoin :
      IntermediateField.adjoin (Base place) {generator} ≤
        IntermediateField.adjoin (Base place) {root} :=
    IntermediateField.adjoin_simple_le_iff.mpr generatorMemRootAdjoin
  have generatedFieldsEqual :
      IntermediateField.adjoin (Base place) {generator} =
        IntermediateField.adjoin (Base place) {root} := by
    letI : FiniteDimensional (Base place)
        (IntermediateField.adjoin (Base place) {root}) :=
      IntermediateField.adjoin.finiteDimensional rootIntegral
    apply IntermediateField.eq_of_le_of_finrank_le
      generatorAdjoinLeRootAdjoin
    rw [IntermediateField.adjoin.finrank rootIntegral,
      IntermediateField.adjoin.finrank generatorIntegral]
    calc
      (minpoly (Base place) root).natDegree ≤ localPolynomial.natDegree :=
        Polynomial.natDegree_le_of_dvd
          (minpoly.dvd (Base place) root
            (Polynomial.mem_aroots.mp rootOfLocalPolynomial).2)
          localMonic.ne_zero
      _ = globalPolynomial.natDegree :=
        globalPolynomial.natDegree_map _
      _ = f.natDegree := sameDegree.symm
      _ = (minpoly (Base place) generator).natDegree := rfl
  refine ⟨globalPolynomial, root, ?_, generatedFieldsEqual⟩
  exact Polynomial.mem_rootSet.mpr
    (Polynomial.mem_aroots.mp rootOfLocalPolynomial)

/-- Every finite Galois local stage is the normal closure generated by a root
of a polynomial over the global number field. -/
theorem exists_global_polynomial_root_generating_stage
    (place : NumberField.FinitePlace K) (stage : StageIndex place) :
    ∃ globalPolynomial : Polynomial K, ∃ root : Closure place,
      root ∈
          (globalPolynomial.map (algebraMap K (Base place))).rootSet
            (Closure place) ∧
        FiniteGaloisIntermediateField.adjoin (Base place) {root} = stage := by
  obtain ⟨generator, generatorGeneratesStage⟩ :=
    exists_stage_primitive_generator place stage
  obtain ⟨globalPolynomial, root, rootOfGlobalPolynomial,
      generatorAdjoinEqRootAdjoin⟩ :=
    exists_global_polynomial_root_same_adjoin place generator
  have rootGeneratesStage :
      IntermediateField.adjoin (Base place) {root} =
        stage.toIntermediateField :=
    generatorAdjoinEqRootAdjoin.symm.trans generatorGeneratesStage
  refine ⟨globalPolynomial, root, rootOfGlobalPolynomial, ?_⟩
  apply le_antisymm
  · exact FiniteGaloisIntermediateField.adjoin_simple_le_iff.mpr <| by
      rw [← rootGeneratesStage]
      exact IntermediateField.subset_adjoin (Base place) {root}
        (Set.mem_singleton root)
  · rw [FiniteGaloisIntermediateField.le_iff, ← rootGeneratesStage]
    exact IntermediateField.adjoin_simple_le_iff.mpr <|
      FiniteGaloisIntermediateField.subset_adjoin (Base place) {root}
        (Set.mem_singleton root)

/-- A countable witness type: a global polynomial together with one of the
finitely many roots of its scalar extension to the algebraic closure. -/
noncomputable def GlobalPolynomialRoot
    (place : NumberField.FinitePlace K) :=
  Σ globalPolynomial : Polynomial K,
    ↥((globalPolynomial.map (algebraMap K (Base place))).rootSet
      (Closure place)).toFinset

noncomputable instance globalPolynomialRootCountable
    (place : NumberField.FinitePlace K) :
    Countable (GlobalPolynomialRoot place) := by
  letI : Countable K := Finsupp.Countable.of_moduleFinite (R := ℚ)
  letI : Countable (AddMonoidAlgebra K ℕ) := instCountableFinsupp
  letI : Countable (Polynomial K) :=
    (Polynomial.toFinsuppIso K).injective.countable
  unfold GlobalPolynomialRoot
  infer_instance

/-- The finite Galois stage generated by a global-polynomial root witness. -/
noncomputable def globalPolynomialRootStage
    (place : NumberField.FinitePlace K) :
    GlobalPolynomialRoot place → StageIndex place :=
  fun witness =>
    FiniteGaloisIntermediateField.adjoin (Base place)
      {(witness.2.1 : Closure place)}

/-- Global-polynomial root witnesses generate every finite Galois local
stage. -/
theorem globalPolynomialRootStage_surjective
    (place : NumberField.FinitePlace K) :
    Function.Surjective (globalPolynomialRootStage place) := by
  intro stage
  obtain ⟨globalPolynomial, root, rootOfGlobalPolynomial, generatesStage⟩ :=
    exists_global_polynomial_root_generating_stage place stage
  refine
    ⟨⟨globalPolynomial,
        ⟨root, Set.mem_toFinset.mpr rootOfGlobalPolynomial⟩⟩,
      ?_⟩
  exact generatesStage

/-- There are only countably many finite Galois subextensions of the
algebraic closure of a number-field completion. -/
noncomputable instance stageIndexCountable
    (place : NumberField.FinitePlace K) :
    Countable (StageIndex place) :=
  (globalPolynomialRootStage_surjective place).countable

/-- The strict positive-integer-style cofinal presentation required by the
paper, now with its arithmetic countability input discharged. -/
noncomputable def integralIndSourceSequentialPresentation
    (place : NumberField.FinitePlace K) :
    (integralIndSystem place).SequentialCofinalPresentation :=
  integralIndSequentialPresentation place

end

end SourceFinitePlaceReconstruction

end


end Iut
