/-
Copyright (c) 2026 IUT Lean formalization contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: IUT Lean formalization contributors
-/
import Iut.Foundations.SourceConjugateSynchronization
import Iut.Foundations.SourceThetaSplitting

/-!
# Source Hodge--Arakelov theta pilots

This module assembles the actual continuous-cohomology theta values used in
IUT II with the `q^(j^2)` pilot profile.  It is deliberately separate from the
finite real-degree model in `Iut.Stage1.IUTStage1HodgeArakelovPilots`.

The input records the paper-level evaluation statements: the `q`-powers lie
in the evaluated `mu_(2l)` theta orbits, compatible positive roots lie in the
infinite-theta orbits, and those infinite orbits satisfy Proposition 1.4's
power-up-to-torsion relation.  Gaussian monoids, profile independence, orbit
cardinalities, and the value-profile cardinality are derived from these data.
-/

namespace Iut

universe u

/--
The source Hodge--Arakelov `q`-pilot and all of its theta values in continuous
`H^1` germs.

The `mu_(2l)` cardinality is retained as the exact source fact identifying the
acting roots-of-unity group.  Freeness and all orbit/profile cardinalities are
derived from the injective multiplicative action.
-/
structure SourceIUTIIHodgeArakelovThetaPilot
    {G A Mu2l Mu : Type u}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [Group A] [TopologicalSpace A] [IsTopologicalGroup A]
    [IsMulCommutative A]
    (l : PrimeGeFive)
    (action : ContinuousGroupAction G A)
    [Group Mu2l] [Finite Mu2l]
    [Group Mu]
    [MulAction Mu2l (ContinuousH1Germ action)]
    [MulAction Mu (ContinuousH1Germ action)]
    (orbits :
      SourceIUTIIThetaEvaluationOrbits
        (G := G) (A := A)
        (Mu2l := Mu2l) (Mu := Mu)
        l action)
    (multiplicative :
      SourceIUTIIMultiplicativeTorsionAction
        l Mu2l (ContinuousH1Germ action)) where
  qPilot : ContinuousH1Germ action
  one_mem_zeroTheta :
    1 ∈
      (orbits.theta
        IUTIIAbsoluteThetaLabel.zero).carrier
  thetaPower_mem :
    ∀ j : IUTIPositiveLabel.{u} l,
      thetaPowerValueProfile l qPilot j ∈
        (orbits.theta
          (IUTIIAbsoluteThetaLabel.nonzero
            (IUTIPositiveLabel.signLabel j))).carrier
  infiniteTheta_relation :
    SourceIUTIIInfiniteThetaRelation orbits
  roots :
    ValueProfileRootSystem
      (thetaPowerValueProfile l qPilot)
  roots_mem_infiniteTheta :
    ∀ (N : ℕ+) (j : IUTIPositiveLabel.{u} l),
      roots.root N j ∈
        (orbits.infiniteTheta
          (IUTIIAbsoluteThetaLabel.nonzero
            (IUTIPositiveLabel.signLabel j))).carrier
  mu2l_card :
    Nat.card Mu2l = 2 * l.value

namespace SourceIUTIIHodgeArakelovThetaPilot

variable
  {G A Mu2l Mu : Type u}
  [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [Group A] [TopologicalSpace A] [IsTopologicalGroup A]
  [IsMulCommutative A]
  {l : PrimeGeFive}
  {action : ContinuousGroupAction G A}
  [Group Mu2l] [Finite Mu2l]
  [Group Mu]
  [MulAction Mu2l (ContinuousH1Germ action)]
  [MulAction Mu (ContinuousH1Germ action)]
  {orbits :
    SourceIUTIIThetaEvaluationOrbits
      (G := G) (A := A)
      (Mu2l := Mu2l) (Mu := Mu)
      l action}
  {multiplicative :
    SourceIUTIIMultiplicativeTorsionAction
      l Mu2l (ContinuousH1Germ action)}

/-- The torsion-orbit family derived from the evaluated theta orbits. -/
def thetaFamily
    (_pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    SourceIUTIITorsionThetaValueFamily
      l (ContinuousH1Germ action) :=
  orbits.toTorsionThetaValueFamily multiplicative

/-- The simultaneous value profile consisting of the actual `q^(j^2)` values. -/
def thetaPowerProfile
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    SourceIUTIIValueProfile
      l pilot.thetaFamily.thetaValues where
  toFun := thetaPowerValueProfile l pilot.qPilot
  mem_thetaValues := by
    intro j
    change
      thetaPowerValueProfile l pilot.qPilot j ∈
        (orbits.toTorsionThetaValueFamily
          multiplicative).thetaValues
            (IUTIIAbsoluteThetaLabel.nonzero
              (IUTIPositiveLabel.signLabel j))
    rw [SourceIUTIIThetaEvaluationOrbits.toTorsionThetaValueFamily_thetaValues]
    exact pilot.thetaPower_mem j

@[simp]
theorem thetaPowerProfile_apply
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative)
    (j : IUTIPositiveLabel.{u} l) :
    pilot.thetaPowerProfile j =
      pilot.qPilot ^
        (IUTIPositiveLabel.representative j) ^ 2 :=
  rfl

/-- The finite Gaussian monoid generated by the evaluated theta pilot. -/
def finiteGaussianMonoid
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    Submonoid
      (IUTIPositiveLabel.{u} l →
        ContinuousH1Germ action) :=
  sourceGaussianMonoid pilot.thetaPowerProfile

/-- The rational-root Gaussian monoid generated by infinite-theta values. -/
def infiniteGaussianMonoid
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    Submonoid
      (IUTIPositiveLabel.{u} l →
        ContinuousH1Germ action) :=
  sourceInfiniteGaussianMonoid pilot.roots

theorem thetaPowerProfile_mem_finiteGaussianMonoid
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    (pilot.thetaPowerProfile :
        IUTIPositiveLabel.{u} l →
          ContinuousH1Germ action) ∈
      pilot.finiteGaussianMonoid :=
  sourceGaussianMonoid.profile_mem pilot.thetaPowerProfile

theorem roots_mem_infiniteGaussianMonoid
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative)
    (N : ℕ+) :
    pilot.roots.root N ∈
      pilot.infiniteGaussianMonoid :=
  sourceInfiniteGaussianMonoid.root_mem pilot.roots N

/--
The `2l`-multiple Gaussian submonoid of the `q^(j^2)` profile is the canonical
profile-independent submonoid of its entire theta-orbit family.
-/
theorem twoEllGaussianSubmonoid_eq_profileIndependent
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    sourceTwoEllGaussianSubmonoid
        l pilot.thetaPowerProfile =
      pilot.thetaFamily.profileIndependentTwoEllGaussianSubmonoid l :=
  pilot.thetaFamily.twoEllGaussianSubmonoid_eq_profileIndependent
    l pilot.thetaPowerProfile

/-- Every evaluated theta orbit has exactly `2l` elements. -/
theorem thetaOrbit_natCard
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative)
    (label : IUTIIAbsoluteThetaLabel.{u} l) :
    Nat.card (orbits.theta label).carrier =
      2 * l.value :=
  (GroupActionOrbit.natCard_carrier_eq_group
      (orbits.theta label)
      (multiplicative.actionMap_injective
        (orbits.theta label).representative)).trans
    pilot.mu2l_card

/--
The total set of theta value-profiles has the Corollary 3.5(ii) cardinality
`(2l)^(l*)`.
-/
theorem valueProfiles_natCard
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    Nat.card
        (SourceIUTIIValueProfile l
          (fun label => (orbits.theta label).carrier)) =
      (2 * l.value) ^ l.lStar := by
  classical
  letI :
      ∀ j : IUTIPositiveLabel.{u} l,
        Finite
          { value : ContinuousH1Germ action //
            value ∈
              (orbits.theta
                (IUTIIAbsoluteThetaLabel.nonzero
                  (IUTIPositiveLabel.signLabel j))).carrier } :=
    fun j =>
      Finite.of_equiv Mu2l
        (GroupActionOrbit.groupEquivCarrier
          (orbits.theta
            (IUTIIAbsoluteThetaLabel.nonzero
              (IUTIPositiveLabel.signLabel j)))
          (multiplicative.actionMap_injective
            (orbits.theta
              (IUTIIAbsoluteThetaLabel.nonzero
                (IUTIPositiveLabel.signLabel j))).representative))
  apply SourceIUTIIValueProfile.natCard_eq_twoEll_pow_lStar
  intro j
  exact pilot.thetaOrbit_natCard
    (IUTIIAbsoluteThetaLabel.nonzero
      (IUTIPositiveLabel.signLabel j))

/-- The zero-label theta orbit consists entirely of torsion classes. -/
theorem zeroTheta_carrier_subset_torsion
    (pilot :
      SourceIUTIIHodgeArakelovThetaPilot
        l action orbits multiplicative) :
    (orbits.theta IUTIIAbsoluteThetaLabel.zero).carrier ⊆
      CommGroup.torsion
        (ContinuousH1Germ action) := by
  intro value hvalue
  rcases pilot.one_mem_zeroTheta with
    ⟨zeroScalar, hzeroScalar⟩
  rcases hvalue with ⟨valueScalar, hvalueScalar⟩
  change
    zeroScalar •
        (orbits.theta
          IUTIIAbsoluteThetaLabel.zero).representative =
      1 at hzeroScalar
  change
    valueScalar •
        (orbits.theta
          IUTIIAbsoluteThetaLabel.zero).representative =
      value at hvalueScalar
  have representative_eq :
      (orbits.theta IUTIIAbsoluteThetaLabel.zero).representative =
        ((multiplicative.unitEmbedding zeroScalar :
          (ContinuousH1Germ action)ˣ) :
          ContinuousH1Germ action)⁻¹ := by
    rw [multiplicative.smul_eq_unit_mul] at hzeroScalar
    apply eq_inv_of_mul_eq_one_left
    simpa only [mul_comm] using hzeroScalar
  rw [← hvalueScalar, multiplicative.smul_eq_unit_mul,
    representative_eq]
  exact
    (CommGroup.torsion
      (ContinuousH1Germ action)).mul_mem
      (multiplicative.toFiniteOrderAction.unitEmbedding_isOfFinOrder
        valueScalar)
      ((CommGroup.torsion
        (ContinuousH1Germ action)).inv_mem
          (multiplicative.toFiniteOrderAction.unitEmbedding_isOfFinOrder
            zeroScalar))

end SourceIUTIIHodgeArakelovThetaPilot

end Iut
